### ISSUE TITLE
Converting scalaapi.ComposableFuture to java ComposableFuture

### ISSUE THREAD

**Issue by anatolyra** [outbrain/ob1k#17]
Hi,

There is no easy way of converting the scala ComposableFuture (ob1k/ob1k-concurrent-scala/src/main/scala/com/outbrain/ob1k/concurrent/scalaapi/ComposableFuture.scala) to it's java counterpart. There should be a method available in the ComposableFuture object (an implicit or explicit one) that enables the user to easily convert it.

Thanks!

**Comment by marenzo** [comment]
I'll release new version with the new metod soon.
